/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ta_feature;
import java.io.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
/**
 *
 * @author rlarh
 */
public class ApprovedFrame extends javax.swing.JFrame {
private void loadApprovedReservations() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // 테이블 변수명 맞게!
    model.setRowCount(0); // 기존 데이터 초기화

    String path = "C:\\Users\\rlarh\\OneDrive\\바탕 화면\\reservations_approved.txt";

    try (BufferedReader br = new BufferedReader(new FileReader(path))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] tokens = line.split(",");
            if (tokens.length == 7 && tokens[6].equals("승인")) {
                model.addRow(tokens); // 한 줄 추가
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "승인 내역을 불러오는 중 오류 발생!");
        e.printStackTrace();
    }
}
private void appendLog(String beforeStatus, String afterStatus,
                       String name, String room, String date,
                       String start, String end, String people) {
    String timestamp = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new java.util.Date());

    String action;
    if (beforeStatus.equals("대기")) {
        action = afterStatus + "됨";  // 승인됨, 거절됨
    } else {
        action = String.format("상태 변경: %s → %s", beforeStatus, afterStatus);
    }

    String line = String.format("[%s] %s - %s, %s, %s, %s~%s, %s명",
                    timestamp, action, name, room, date, start, end, people);

    String path = "C:\\Users\\rlarh\\OneDrive\\바탕 화면\\reservation_log.txt";

    try (BufferedWriter bw = new BufferedWriter(new FileWriter(path, true))) {
        bw.write(line);
        bw.newLine();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "로그 저장 실패!");
    }
}
    /**
     * Creates new form ApprovedFrame
     */
    public ApprovedFrame() {
        initComponents();
         loadApprovedReservations();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("승인 내역");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "이름", "강의실", "날짜", "시작 시간", "종료 시간", "인원 수", "상태"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("거절");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("이전");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addComponent(jButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    new featureFrame().setVisible(true); // 학사조교 창 다시 열기
    this.dispose(); // 현재 창 닫기
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "예약을 선택하세요.");
        return;
    }

    String name = jTable1.getValueAt(row, 0).toString();
    String room = jTable1.getValueAt(row, 1).toString();
    String date = jTable1.getValueAt(row, 2).toString();
    String start = jTable1.getValueAt(row, 3).toString();
    String end = jTable1.getValueAt(row, 4).toString();
    String people = jTable1.getValueAt(row, 5).toString();
    String status = "승인";

    String targetLine = String.join(",", name, room, date, start, end, people, status);

    String approvedPath = "C:\\Users\\rlarh\\OneDrive\\바탕 화면\\reservations_approved.txt";
    String rejectedPath = "C:\\Users\\rlarh\\OneDrive\\바탕 화면\\reservations_rejected.txt";

    List<String> lines = new ArrayList<>();

    try (BufferedReader br = new BufferedReader(new FileReader(approvedPath))) {
        String line;
        while ((line = br.readLine()) != null) {
            if (!line.equals(targetLine)) {
                lines.add(line); // 삭제 제외
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "승인 목록 읽기 오류!");
        return;
    }

    try (BufferedWriter bw = new BufferedWriter(new FileWriter(approvedPath))) {
        for (String l : lines) {
            bw.write(l);
            bw.newLine();
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "승인 목록 쓰기 오류!");
        return;
    }

    String rejectedLine = String.join(",", name, room, date, start, end, people, "거절");
    try (BufferedWriter bw = new BufferedWriter(new FileWriter(rejectedPath, true))) {
        bw.write(rejectedLine);
        bw.newLine();
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "거절 내역 저장 실패!");
        return;
    }

    JOptionPane.showMessageDialog(this, "해당 예약이 거절로 변경되었습니다.");
    loadApprovedReservations(); // 새로고침
    appendLog("승인", "거절", name, room, date, start, end, people);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApprovedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApprovedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApprovedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApprovedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApprovedFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
